on:
  issues:
    types: [opened]

name: Sync Github Issues in Jira

jobs:
  github-issue-jira-sync:
    name: Sync Issues
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://warthogs.atlassian.net
        JIRA_USER_EMAIL: yazan.salti@canonical.com
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Bug
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: "Telco-ENG (TELCO)"
        issuetype: Bug
        summary: ${{ github.event.issue.title }}
