name: Integration tests

on:
  workflow_call:
    inputs:
      artifacts-key:
        description: Key used to download the charm artifacts
        required: true
        type: string
      charm-paths:
        description: Comma-separated list of built charm file names
        required: true
        type: string
      runner:
        description: GitHub Actions runner label(s) as a JSON string
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ${{ fromJson(inputs.runner) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Fetch Charm Under Test
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifacts-key }}
          path: built/

      - name: Get Charm Under Test Path
        id: charm-path
        run: echo "charm_path=$(find built/ -name '*.charm' -type f -print)" >> $GITHUB_OUTPUT

      # Configuring manually instead of using the charmed-kubernetes/actions-operator@main
      # so we can run sudo microk8s config | juju add-k8s my-k8s --client before bootstrap
      # This workaround is needed because ARM runners are failing to setup strictly confined microk8s
      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Install Juju
        run: |
          sudo snap install juju --channel=3.6/stable

      - name: Install and setup Microk8s
        run: |
          sudo snap install microk8s --channel=1.32/stable --classic
          sudo microk8s enable dns storage rbac

      - name: Wait for Microk8s to be ready
        run: |
          sudo microk8s status --wait-ready

      - name: Add Microk8s to Juju
        run: |
          sudo microk8s config | juju add-k8s my-k8s --client

      - name: Bootstrap Juju controller
        run: |
          juju bootstrap my-k8s github-pr-${{ github.run_id }}-microk8s --debug --verbose

      - name: Install UV and Tox
        run: |
          pipx uninstall tox || true
          sudo snap install astral-uv --classic
          uv tool install tox --with tox-uv --force

      - name: Run integration tests
        run: |
          tox -e integration -- \
            --charm_path="${{ steps.charm-path.outputs.charm_path }}" \

      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log

      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: juju-crashdump
          path: juju-crashdump-*.tar.xz
