name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      arch:
        type: choice
        description: Architecture
        options:
          - amd64
          - arm64

jobs:
  promote:
    name: Promote Charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set target channel
        env:
          PROMOTE_FROM: ${{ github.event.inputs.promotion }}
        run: |
          if [ "${PROMOTE_FROM}" == "edge -> beta" ]; then
            echo "promote-from=edge" >> ${GITHUB_ENV}
            echo "promote-to=beta" >> ${GITHUB_ENV}
          elif [ "${PROMOTE_FROM}" == "beta -> candidate" ]; then
            echo "promote-from=beta" >> ${GITHUB_ENV}
            echo "promote-to=candidate" >> ${GITHUB_ENV}
          elif [ "${PROMOTE_FROM}" == "candidate -> stable" ]; then
            echo "promote-from=candidate" >> ${GITHUB_ENV}
            echo "promote-to=stable" >> ${GITHUB_ENV}
          fi
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: 1/${{ env.promote-to }}
          origin-channel: 1/${{ env.promote-from }}
          charmcraft-channel: 1/stable
          base-channel: "24.04"
          base-architecture: ${{ github.event.inputs.arch }}
