name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      arch:
        type: choice
        description: Architecture
        options:
          - amd64
          - arm64

env:
  PROMOTE_FROM: ${{ inputs.promotion == 'edge -> beta' && 'edge' || inputs.promotion == 'beta -> candidate' && 'beta' || inputs.promotion == 'candidate -> stable' && 'candidate' || '' }}
  PROMOTE_TO: ${{ inputs.promotion == 'edge -> beta' && 'beta' || inputs.promotion == 'beta -> candidate' && 'candidate' || inputs.promotion == 'candidate -> stable' && 'stable' || '' }}
  TRACK: "1" # This also needs to be updated in the scan job below

jobs:
  scan:
    name: Secscan
    uses: canonical/identity-credentials-workflows/.github/workflows/secscan-charm.yaml@v0
    with:
      charm: manual-tls-certificates
      track: "1"
      # We have to compute the channel here again because we can't pass env variables to a reusable workflow
      channel: ${{ inputs.promotion == 'edge -> beta' && 'edge' || inputs.promotion == 'beta -> candidate' && 'beta' || inputs.promotion == 'candidate -> stable' && 'candidate' || '' }}
      arch: amd64
      create-issue: ${{ inputs.promotion == 'candidate -> stable' || inputs.promotion == 'beta -> candidate' }}

  promote:
    name: Promote Charm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: ${{ env.TRACK }}/${{ env.PROMOTE_TO }}
          origin-channel: ${{ env.TRACK }}/${{ env.PROMOTE_FROM }}
          charmcraft-channel: latest/stable
          base-channel: "24.04"
          base-architecture: ${{ github.event.inputs.arch }}
