name: Scan UV dependencies

on:
  push:
    branches:
      - main

jobs:
  scan:
    permissions:
      security-events: write
      actions: read
      contents: read
    uses: canonical/identity-credentials-workflows/.github/workflows/uv-scan.yaml@v0
